### ISSUE TITLE
Create a Advanced Inscriber

### ISSUE THREAD

**Issue by pd200** [gliscowo/mass-inscriber#1]
You could add a new block, the Advanced Inscriber, which has more card slots and faster speed than the standard Inscriber, like that of the ae2 stuff.

**Comment by gliscowo** [comment]
I might do that at some point, however that would be in a different mod and not guaranteed. The whole idea behind this was for it to be a lightweight thing I can throw together in a hour, cause I needed it personally

Cheers

**Comment by pd200** [comment]
> I might do that at some point, however that would be in a different mod and not guaranteed. The whole idea behind this was for it to be a lightweight thing I can throw together in a hour, cause I needed it personally
> 
> Cheers


Maybe you could combine the two mods, in fact, if you remember, the advanced inscriber of the ae2 stuff could have a whole stack of the materials had more card slots and ran faster.

Crafting could be the following (I am attaching a photo).
The materials are (4k ME storage, accelerator card, capacity card, and fluix block)


![image](https://user-images.githubusercontent.com/47245832/105467414-f5e15580-5c95-11eb-8413-3f5b3ae1cc8c.png)
